name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --no-cache -t zz212224236/snapgoated-services:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push zz212224236/snapgoated-services:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              # Update EC2 and install Docker (if not already installed)
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              
              # Docker login (corrected syntax)
              echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              
              # Remove all Docker images
              sudo docker rmi -f $(sudo docker images -q) || true
              
              # Pull the latest Docker image from Docker Hub
              sudo docker pull zz212224236/snapgoated-services:${{ github.sha }}
              
              # Stop and remove the old container (if any)
              sudo docker stop snapgoated-services || true
              sudo docker rm snapgoated-services || true
              
              # Run the new Docker container
              sudo docker run -d --name snapgoated-services --restart unless-stopped -p 8000:8000 zz212224236/snapgoated-services:${{ github.sha }}
              
              # Optionally, clean up unused Docker images
              sudo docker system prune -f
              
              # Verify that the container is running
              sudo docker ps -a
              
              # Optionally, view logs
              sudo docker logs snapgoated-services

              
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_COMMIT: ${{ github.event.head_commit.message }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          GITHUB_SUCCESS="true"
          
          PAYLOAD=$(echo -e "🚀 **Deployment Status: Compleated**\n  **Repository:** $GITHUB_REPO\n  **By:** $GITHUB_ACTOR\n  **Commit:** $GITHUB_COMMIT\n  **[View Action]($GITHUB_RUN_URL)**" | jq -R --slurp '{content: .}')
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               $DISCORD_WEBHOOK
