name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t fastapi-app .

    - name: Push Docker image to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > aws-ec2-key.pem
        chmod 600 aws-ec2-key.pem
        scp -o StrictHostKeyChecking=no -i aws-ec2-key.pem docker-compose.yml $EC2_USER@$EC2_HOST:/home/ubuntu/
        ssh -o StrictHostKeyChecking=no -i aws-ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
          docker-compose down
          docker-compose up -d
        EOF